use goatbatch;
select *from orders;
select *from customers;
select *from restaurants;

# Display all completed orders along with customer name and restaurant name
select o.order_id,c.customer_name,r.restaurant_name,o.order_date,o.order_amount from orders o join customers c on o.customer_id = c.customer_id join restaurants r on o.restaurant_id where o.order_status = 'Completed';

# Find the total revenue generated by each restaurant. 
select r.restaurant_name,sum(o.order_amount) as total_revenue from orders o join restaurants r on o.restaurant_id = r.restaurant_id GROUP by r.restaurant_name;

# Show the total number of orders placed by each customer. 
SELECT c.customer_name,count(o.order_id) as Total_orders from customers c left join orders o on c.customer_id = o.customer_id group by c.customer_name;

# Find the average order amount for each city. 
SELECT r.city,avg(o.order_amount) as average_order_amount from orders o join restaurants r on o.restaurant_id = r.restaurant_id group by r.city;

# Categorize orders as Low, Medium, and High based on order amount.
select order_id,order_amount , case when order_amount < 300 then 'low' when order_amount <= 700 then 'medium' else 'high' end as order_category from orders;

# Display restaurants whose average order value is greater than the overall average order value.
SELECT r.restaurant_name, AVG(o.order_amount) AS average_order_value FROM orders o JOIN restaurants r ON o.restaurant_id = r.restaurant_id GROUP BY r.restaurant_name HAVING AVG(o.order_amount) > (SELECT AVG(order_amount) FROM orders);

# Find customers who have never placed any orders. 
SELECT c.customer_id, c.customer_name FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id WHERE o.order_id IS NULL;

# Show the top 5 customers based on total spending. 
SELECT c.customer_name, SUM(o.order_amount) AS total_spending FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_name ORDER BY total_spending DESC LIMIT 5;

# Find the most frequently used payment method. 
SELECT payment_method, COUNT(*) AS usage_count FROM orders GROUP BY payment_method ORDER BY usage_count DESC LIMIT 1;

# Calculate the running total of revenue by order date. 
SELECT order_date, order_amount, SUM(order_amount) OVER (ORDER BY order_date) AS running_total_revenue FROM orders;

# Rank restaurants based on total revenue generated. 
SELECT  r.restaurant_name, SUM(o.order_amount) AS total_revenue, RANK() OVER (ORDER BY SUM(o.order_amount) DESC) AS revenue_rank FROM orders o JOIN restaurants r ON o.restaurant_id = r.restaurant_id GROUP BY r.restaurant_name;

# Find the second highest order amount from the orders table. 
SELECT order_amount FROM (SELECT order_amount,DENSE_RANK() OVER (ORDER BY order_amount DESC) AS amount_rank FROM orders) AS ranked_orders WHERE amount_rank = 2;

# Find customers who placed more orders than the average number of orders per customer. 
SELECT c.customer_name, COUNT(o.order_id) AS total_orders FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_name HAVING COUNT(o.order_id) > (SELECT AVG(order_count) FROM (SELECT customer_id,COUNT(*) AS order_count FROM orders GROUP BY customer_id) AS customer_orders);

# Display the top 3 restaurants in each city based on total orders received. 
SELECT city,restaurant_name,total_orders FROM (SELECT r.city,r.restaurant_name,COUNT(o.order_id) AS total_orders,RANK() OVER (PARTITION BY r.city ORDER BY COUNT(o.order_id) DESC) AS restaurant_rank
    FROM restaurants r
    JOIN orders o
        ON r.restaurant_id = o.restaurant_id
    GROUP BY r.city, r.restaurant_name
) AS ranked_restaurants
WHERE restaurant_rank <= 3;

# Calculate month-wise revenue and show the previous month revenue.
WITH monthly_revenue AS (SELECT DATE_FORMAT(order_date, '%Y-%m') AS order_month,SUM(order_amount) AS revenue FROM orders GROUP BY DATE_FORMAT(order_date, '%Y-%m'))
SELECT order_month,revenue,LAG(revenue) OVER (ORDER BY order_month) AS previous_month_revenue FROM monthly_revenue ORDER BY order_month;